const tools=[
{name:'Gemini',url:'https://gemini.google.com/',category:'image',preferred:true},
{name:'SnapGen',url:'https://snapgen.ai/',category:'animation',max:10,dialogue:true,ambience:true},
{name:'Meta AI',url:'https://www.meta.ai/',category:'animation',max:10,dialogue:true,ambience:true},
{name:'Vibes',url:'https://vibes.ai/',category:'animation',preferred:true,max:10,dialogue:true,ambience:true},
{name:'Grok',url:'https://grok.com/',category:'animation',max:10,dialogue:true,ambience:true}
];
let state=JSON.parse(localStorage.getItem('animartoon-state')||'null')||{page:'Próxima ação',storage:'Google Drive Online',scenes:[
{id:'C002',title:'Abraão ensina as crianças',duration:7.5,type:'Diálogo',characters:['ABRAHAM_01','CHILD_GROUP_01'],location:'CAMP_OASIS_01',image:'done',animation:'done',approved:true},
{id:'C003',title:'Sarah no interior da tenda',duration:2.3,type:'Ambiente/Narração',characters:['SARAH_01'],location:'TENT_INTERIOR_01',image:'done',animation:'pending',approved:false},
{id:'C004',title:'Abraão ensina as crianças',duration:5.2,type:'Diálogo',characters:['ABRAHAM_01','CHILD_GROUP_01'],location:'CAMP_OASIS_01',image:'pending',animation:'pending',approved:false},
{id:'C006',title:'Close de Abraão',duration:8.5,type:'Diálogo',characters:['ABRAHAM_01'],location:'CAMP_OASIS_01',image:'pending',animation:'pending',approved:false}
]};
const pages=['Próxima ação','Projetos','Produção','Personagens','Cenários','Cenas','Mapa de arquivos','Auditoria','Configurações'];
function save(){localStorage.setItem('animartoon-state',JSON.stringify(state))}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function nav(){navEl=document.getElementById('nav');navEl.innerHTML=pages.map(p=>'<button class="'+(state.page===p?'active':'')+'" data-p="'+p+'">'+p+'</button>').join('');navEl.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.page=b.dataset.p;save();render()})}
function progress(){let n=state.scenes.reduce((a,s)=>a+(s.image==='done')+(s.animation==='done')+(s.approved?1:0),0);return Math.round(n/(state.scenes.length*3)*100)}
function next(){return state.scenes.find(s=>s.image!=='done'||s.animation!=='done'||!s.approved)||state.scenes[0]}
function mark(){let s=next();if(s.image!=='done')s.image='done';else if(s.animation!=='done')s.animation='done';else s.approved=true;save();render()}
function copy(t){navigator.clipboard.writeText(t);toast('Copiado')}
function toast(t){let e=document.getElementById('toast')||document.body.appendChild(Object.assign(document.createElement('div'),{id:'toast',className:'toast'}));e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1200)}
function nextView(){let s=next(),image=s.image!=='done',kind=image?'Gerar imagem':s.animation!=='done'?'Gerar animação':'Aprovar cena',file=image?s.id+'_IMG_v01.png':s.id+'_ANIM_v01.mp4',prompt=image?'Create a consistent stylized 3D biblical keyframe for '+s.title+'. Preserve characters, setting and cinematic family-animation look.':'Create a '+s.duration+'-second animation for '+s.title+'. '+(s.type==='Diálogo'?'Include natural synchronized dialogue, character acting and scene ambience.':'No dialogue; animate character/environment motion and ambience.')+' Preserve visual continuity.',tt=tools.filter(t=>t.category===(image?'image':'animation'));
return '<div class="grid"><section class="card span2"><div class="top"><div><p class="eyebrow">PROJETO ATIVO</p><h2>Abraão e Isaque — 3D</h2></div><div class="percent">'+progress()+'%</div></div><div class="progress"><div style="width:'+progress()+'%"></div></div></section><section class="card span2"><div class="section-title"><div><p class="eyebrow">PRÓXIMA AÇÃO</p><h2>'+s.id+' — '+kind+'</h2></div><span class="badge accent">'+s.type+'</span></div><div class="scene-meta"><div><small>Duração</small><strong>'+s.duration.toFixed(1)+' s</strong></div><div><small>Personagens</small><strong>'+esc(s.characters.join(', '))+'</strong></div><div><small>Cenário</small><strong>'+s.location+'</strong></div><div><small>Workflow</small><strong>'+(s.type==='Diálogo'?'vídeo com fala':'vídeo sem fala')+'</strong></div></div>'+(s.duration>10?'<div class="warning">Cena acima de 10 s: sugerir divisão automática.</div>':'')+'<div class="two"><div><span class="label">Nome sugerido</span><div class="panel copybox"><code>'+file+'</code><button class="btn" onclick="copy(\''+file+'\')">Copiar</button></div></div><div><span class="label">Prompt</span><div class="panel"><p class="prompt">'+esc(prompt)+'</p><button class="btn" onclick="copy('+JSON.stringify(prompt)+')">Copiar prompt</button></div></div></div><div class="tools">'+tt.map(t=>'<a class="'+(t.preferred?'preferred':'')+'" href="'+t.url+'" target="_blank">↗ '+t.name+(t.preferred?' • preferida':'')+'</a>').join('')+'</div><button class="btn primary" onclick="mark()">✓ Marcar etapa como concluída</button></section></div>'}
function production(){return '<section class="card"><p class="eyebrow">PIPELINE</p><h2>Produção por cena</h2><div class="table">'+state.scenes.map(s=>'<div class="row"><strong>'+s.id+'</strong><span>'+s.title+'</span><span class="'+(s.image==='done'?'ok':'warn')+'">'+(s.image==='done'?'✓':'○')+' Imagem</span><span class="'+(s.animation==='done'?'ok':'warn')+'">'+(s.animation==='done'?'✓':'○')+' Animação</span><span class="'+(s.approved?'ok':'warn')+'">'+(s.approved?'✓':'○')+' Final</span></div>').join('')+'</div></section>'}
function filemap(){let i=state.scenes.filter(s=>s.image==='done').length,a=state.scenes.filter(s=>s.animation==='done').length,f=state.scenes.filter(s=>s.approved).length,b=[['Personagens',3,4],['Cenários',3,5],['Imagens',i,state.scenes.length],['Animações',a,state.scenes.length],['Cenas finais',f,state.scenes.length]];return '<div class="grid"><section class="card span2"><p class="eyebrow">MAPA DA PRODUÇÃO</p><h2>Progresso por categoria</h2>'+b.map(x=>'<div class="mapline"><div class="topline"><strong>'+x[0]+'</strong><span>'+x[1]+' / '+x[2]+'</span></div><div class="mini"><div style="width:'+x[1]/x[2]*100+'%"></div></div></div>').join('')+'</section></div>'}
function settings(){let modes=['Google Drive Online','Google Drive no computador','Controle manual'];return '<div class="grid"><section class="card span2"><p class="eyebrow">ARMAZENAMENTO</p><h2>Modo do projeto</h2><div class="modes">'+modes.map(m=>'<button class="mode '+(state.storage===m?'selected':'')+'" onclick="setStorage(\''+m+'\')"><strong>'+m+'</strong></button>').join('')+'</div></section><section class="card span2"><p class="eyebrow">FERRAMENTAS</p><h2>Geradores cadastrados</h2><div class="settings-list">'+tools.map(t=>'<div><div class="meta"><strong>'+t.name+'</strong><small class="muted">'+(t.category==='image'?'Imagem':'Animação')+(t.preferred?' • preferida':'')+'</small></div><div class="chips">'+(t.max?'<span class="chip">'+t.max+'s</span>':'')+(t.dialogue?'<span class="chip">fala</span>':'')+(t.ambience?'<span class="chip">ambiente</span>':'')+'</div><a href="'+t.url+'" target="_blank">Abrir ↗</a></div>').join('')+'</div></section></div>'}
function simple(title,text){return '<section class="card"><p class="eyebrow">'+title.toUpperCase()+'</p><h2>'+title+'</h2><p class="muted">'+text+'</p></section>'}
function audit(){let mi=state.scenes.filter(s=>s.image!=='done').length,ma=state.scenes.filter(s=>s.animation!=='done').length;return '<section class="card"><p class="eyebrow">AUDITORIA</p><h2>Verificação do projeto</h2><div class="audit"><div class="panel"><span class="muted">Cenas</span><strong>'+state.scenes.length+'</strong></div><div class="panel"><span class="muted">Imagens faltando</span><strong>'+mi+'</strong></div><div class="panel"><span class="muted">Animações faltando</span><strong>'+ma+'</strong></div><div class="panel"><span class="muted">Fora do padrão</span><strong>0</strong></div></div></section>'}
function setStorage(m){state.storage=m;save();render()}
function render(){nav();document.getElementById('pageTitle').textContent=state.page;document.getElementById('storagePill').textContent=state.storage;let views={'Próxima ação':nextView,'Produção':production,'Mapa de arquivos':filemap,'Auditoria':audit,'Configurações':settings,'Projetos':()=>simple('Projetos','MVP preparado para adaptação de vídeo existente. Projeto original e inspirado em referência ficam previstos para evolução.'),'Personagens':()=>simple('Personagens','Biblioteca de referências e controle de conclusão dos personagens.'),'Cenários':()=>simple('Cenários','Biblioteca de ambientes reutilizáveis do projeto.'),'Cenas':()=>production};document.getElementById('content').innerHTML=views[state.page]()}
render();